=== JanMeritus/tei/CH_Chorinsti/xml/místní_jména_rejstřík_abc.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT jmena (item)+>
<!ATTLIST jmena
  xmlns CDATA #FIXED ''>

<!ELEMENT item (name+,signatura+,výskyt)>
<!ATTLIST item
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''
  ref NMTOKEN #IMPLIED>

<!ELEMENT signatura (#PCDATA)>
<!ATTLIST signatura
  xmlns CDATA #FIXED ''>

<!ELEMENT výskyt (#PCDATA)>
<!ATTLIST výskyt
  xmlns CDATA #FIXED ''>

=== JanMeritus/tei/CH_Chorinsti/xml/místní_jména_rejstřík_abc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jmena SYSTEM "místní_jména_rejstřík_abc.dtd">
<jmena>
   <item>
      <name>Altenbergischen</name>
      <signatura>CH 4</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Amsterdam</name>
      <signatura>CH 38</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Arendall</name>
      <signatura>CH 82</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Argentinensi</name>
      <signatura>CH 82</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Austriae</name>
      <signatura>CH 82</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Bánovce nad Bebravou</name>
      <signatura>CH 95</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Bánovcích nad Bebravou</name>
      <signatura>CH 95</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Banská Štiavnica</name>
      <signatura>CH 4</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Banskou Štiavnicu</name>
      <signatura>CH 4</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Bavorska</name>
      <signatura>CH 63</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Berlin</name>
      <signatura>CH 30</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Bílé Poličany</name>
      <signatura>CH-0004.805</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Böheimb</name>
      <signatura>CH 21</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Bolzano</name>
      <signatura>CH 44</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Bolzanu</name>
      <signatura>CH 44</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Brazílii</name>
      <signatura>CH 78</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Břeclavi</name>
      <signatura>CH 108</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Bresslaw</name>
      <signatura>CH 21</signatura>
      <signatura>CH 21</signatura>
      <výskyt>2</výskyt>
   </item>
   <item>
      <name>Briegk</name>
      <signatura>CH 21</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Brně</name>
      <signatura>CH 1</signatura>
      <signatura>CH 2</signatura>
      <signatura>CH 3</signatura>
      <signatura>CH 4</signatura>
      <signatura>CH 5</signatura>
      <signatura>CH 6</signatura>
      <signatura>CH 7</signatura>
      <signatura>CH 8</signatura>
      <signatura>CH 9</signatura>
      <signatura>CH 10</signatura>
      <signatura>CH 11</signatura>
      <signatura>CH 12</signatura>
      <signatura>CH 13</signatura>
      <signatura>CH 14</signatura>
      <signatura>CH 15</signatura>
      <signatura>CH 16</signatura>
      <signatura>CH 17</signatura>
      <signatura>CH 18</signatura>
      <signatura>CH 18</signatura>
      <signatura>CH 19</signatura>
      <signatura>CH 20</signatura>
      <signatura>CH 20</signatura>
      <signatura>CH 21</signatura>
      <signatura>CH 22</signatura>
      <signatura>CH 23</signatura>
      <signatura>CH 24</signatura>
      <signatura>CH 25</signatura>
      <signatura>CH 26</signatura>
      <signatura>CH 27</signatura>
      <signatura>CH 28</signatura>
      <signatura>CH 29</signatura>
      <signatura>CH 30</signatura>
      <signatura>CH 31</signatura>
      <signatura>CH 32</signatura>
      <signatura>CH 33</signatura>
      <signatura>CH 34</signatura>
      <signatura>CH 35</signatura>
      <signatura>CH 36</signatura>
      <signatura>CH 37</signatura>
      <signatura>CH 38</signatura>
      <signatura>CH 39</signatura>
      <signatura>CH 40</signatura>
      <signatura>CH 41</signatura>
      <signatura>CH 42</signatura>
      <signatura>CH 43b</signatura>
      <signatura>CH 43a</signatura>
      <signatura>CH 44</signatura>
      <signatura>CH 45</signatura>
      <signatura>CH 46</signatura>
      <signatura>CH 47</signatura>
      <signatura>CH 48</signatura>
      <signatura>CH 48</signatura>
      <signatura>CH 49</signatura>
      <signatura>CH 49</signatura>
      <signatura>CH 50</signatura>
      <signatura>CH 51</signatura>
      <signatura>CH 52</signatura>
      <signatura>CH 53</signatura>
      <signatura>CH 54</signatura>
      <signatura>CH 55</signatura>
      <signatura>CH 56</signatura>
      <signatura>CH 57</signatura>
      <signatura>CH 58</signatura>
      <signatura>CH 59</signatura>
      <signatura>CH 60</signatura>
      <signatura>CH 61</signatura>
      <signatura>CH 62</signatura>
      <signatura>CH 63</signatura>
      <signatura>CH 64</signatura>
      <signatura>CH 65</signatura>
      <signatura>CH 66</signatura>
      <signatura>CH 67</signatura>
      <signatura>CH 68</signatura>
      <signatura>CH 69</signatura>
      <signatura>CH 70</signatura>
      <signatura>CH 71</signatura>
      <signatura>CH 72</signatura>
      <signatura>CH 73</signatura>
      <signatura>CH 74</signatura>
      <signatura>CH 75</signatura>
      <signatura>CH 76</signatura>
      <signatura>CH 77</signatura>
      <signatura>CH 78</signatura>
      <signatura>CH 79</signatura>
      <signatura>CH 80</signatura>
      <signatura>CH 81</signatura>
      <signatura>CH 82</signatura>
      <signatura>CH 83</signatura>
      <signatura>CH 84</signatura>
      <signatura>CH 85</signatura>
      <signatura>CH 86</signatura>
      <signatura>CH 87</signatura>
      <signatura>CH 87</signatura>
      <signatura>CH 88</signatura>
      <signatura>CH 89</signatura>
      <signatura>CH 89</signatura>
      <signatura>CH 90</signatura>
      <signatura>CH 91</signatura>
      <signatura>CH 92</signatura>
      <signatura>CH 93</signatura>
      <signatura>CH 94</signatura>
      <signatura>CH 95</signatura>
      <signatura>CH 96</signatura>
      <signatura>CH 97</signatura>
      <signatura>CH 98</signatura>
      <signatura>CH 99</signatura>
      <signatura>CH 100</signatura>
      <signatura>CH 100</signatura>
      <signatura>CH 100</signatura>
      <signatura>CH 101</signatura>
      <signatura>CH 102</signatura>
      <signatura>CH 103</signatura>
      <signatura>CH 104</signatura>
      <signatura>CH 105</signatura>
      <signatura>CH 106</signatura>
      <signatura>CH 107</signatura>
      <signatura>CH 108</signatura>
      <signatura>CH 109</signatura>
      <signatura>CH 110</signatura>
      <signatura>CH 111</signatura>
      <signatura>CH 112</signatura>
      <signatura>CH-0006.225</signatura>
      <signatura>CH 113</signatura>
      <signatura>CH-0004.805</signatura>
      <signatura>CH-0005.748</signatura>
      <signatura>CH-0005.959</signatura>
      <signatura>CH-0007.040</signatura>
      <výskyt>127</výskyt>
   </item>
   <item>
      <name>brněnského</name>
      <signatura>CH 22</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Brno</name>
      <signatura>CH 2</signatura>
      <signatura>CH 18</signatura>
      <signatura>CH 21</signatura>
      <signatura>CH 22</signatura>
      <signatura>CH 24</signatura>
      <signatura>CH 48</signatura>
      <signatura>CH 73</signatura>
      <signatura>CH 89</signatura>
      <signatura>CH 97</signatura>
      <signatura>CH 100</signatura>
      <signatura>CH-0004.805</signatura>
      <výskyt>11</výskyt>
   </item>
   <item>
      <name>Brunensibus</name>
      <signatura>CH 48</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Brünn</name>
      <signatura>CH 97</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Brzeg</name>
      <signatura>CH 21</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Carnoviensis</name>
      <signatura>CH 21</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Čáslavic</name>
      <signatura>CH 42</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Čáslavice</name>
      <signatura>CH 42</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Česká Domaslav u Teplé</name>
      <signatura>CH 16</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Choryně</name>
      <signatura>CH 50</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Choryni</name>
      <signatura>CH 50</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Chorynie</name>
      <signatura>CH 50</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Chvalkovice</name>
      <signatura>CH 68</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Chwalkowiczych</name>
      <signatura>CH 68</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Cöllen</name>
      <signatura>CH 28</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Domaslav</name>
      <signatura>CH 16</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Eibenstock</name>
      <signatura>CH 4</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Eibenstocku</name>
      <signatura>CH 4</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Franckfurt am Mayn</name>
      <signatura>CH-0006.225</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Franckfurt am Meyn</name>
      <signatura>CH-0006.225</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Francofurti ad Moenum</name>
      <signatura>CH 82</signatura>
      <výskyt>1</výskyt>
   </item>
   <item>
      <name>Frankfurt am Main</name>
      <signatura>CH 12</signatura>
      <signatura>CH 39</signatura>
      <signatura>CH 82</signatura>
      <signatura>CH 112</signatura>
      <signatura>CH-0006.225</signatura>
      <signatura>CH-0005.959</signatura>
      <výskyt>6</výskyt>
   </item>
   <item>
      <name>Frankfurtu nad Mohanem</name>
      <signatura>CH 39</signatura>
      <signatura>CH 112</signatura>
      <výskyt>2</výskyt>
   </item>
